---
- name: Backup de la base de datos de Mediawiki
  hosts: mediawiki
  become: yes
  vars_files:
    - secrets.yml 
  tasks:
    - name: Crear un directorio para el backup
      file:
        path: /backup/mediawiki
        state: directory
        mode: '0755'

    - name: Hacer un backup de la base de datos desde el host
      shell: >
        mysqldump -h {{ db_host }} -P 5432 -u {{ db_user }} -p{{ db_password }} {{ db_name }} | gzip > /backup/mediawiki/wikidb_backup.sql.gz
      environment:
        MYSQL_PWD: "{{ db_password }}"
      register: backup_result

    - name: Comprobar si el backup fue exitoso
      debug:
        var: backup_result
