pipeline {
    agent any

    environment {
        WORK_DIR = "/var/jenkins_home/${BUILD_ID}"
        MINIKUBE_WORK_DIR = "/home/produccion"
        DOCKER_IMAGE_NAME = "ronniemezzapesa/tp-credicoop"
        DOCKER_IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out SCM-Jobs Project'
                dir("${WORK_DIR}") {
                    git branch: 'main',
                        credentialsId: '65f60e0e-fc4d-4b24-a652-b4d214daf024',
                        url: 'https://github.com/ronniemezzapesa/TP-Grupo01-Credicoop.git'
                }
            }
        }

        stage('Build') {
            steps {
                echo 'Building the application'
                dir("${WORK_DIR}/APPx-API") {
                    sh 'mvn clean package' 
                }
            }
        }

        stage("SonarQube Analysis") {
            steps {
                echo 'SonarQube Analysis'
                script {
                    def scannerHome = tool 'SonarScanner 6.2';
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=ronniemezzapesa_TP-Grupo01-Credicoop_c46de8d2-3e4f-454c-a6e5-6208e6eb9477 \
                            -Dsonar.sources=${WORK_DIR}/APPx-API \
                            -Dsonar.projectBaseDir=${WORK_DIR}/APPx-API
                        """
                    }
                }
            }
        }

        stage('Checkout remoto') {
            agent {
                label 'minikube'
            }
            steps {
                script {
                    echo 'Checking out SCM Jobs Project'
                    git branch: 'main',
                        credentialsId: '65f60e0e-fc4d-4b24-a652-b4d214daf024',
                        url: 'https://github.com/ronniemezzapesa/TP-Grupo01-Credicoop.git'
                }
            }
        }

        stage('Docker Build') {
            agent {
                label 'minikube'
            }
            steps {
                echo 'Building Docker Image'
                dir("${WORK_DIR}/APPx-API") {
                    sh "docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ."
                }
            }
        }

        stage('Docker Push') {
            agent { label 'minikube' }
            steps {
                echo 'Pushing Docker Image'
                sh """
                    docker tag ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
                    docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
                """
            }
        }

        stage('Restart Deployment') {
            agent { label 'minikube' }
            steps {
                script {
                    sh """
                        minikube kubectl rollout restart deployment appx-api-deployment
                        minikube kubectl rollout status deployment appx-api-deployment
                    """
                }
            }
        }
    }
}
