pipeline {
    agent any

    environment {
        WORK_DIR = "/var/jenkins_home/${BUILD_ID}"
        MINIKUBE_WORK_DIR = "/home/produccion"
        DOCKER_IMAGE_NAME = "ronniemezzapesa/tp-credicoop"
        DOCKER_IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out SCM-Jobs Project'
                dir("${WORK_DIR}") {
                    git branch: 'main',
                        credentialsId: '12981d9c-635c-44b8-b0d2-739415ee7e77',
                        url: 'https://github.com/ronniemezzapesa/TP-Grupo01-Credicoop.git'
                }
            }
        }

        stage('Build') {
            steps {
                echo 'Building the application'
                dir("${WORK_DIR}/APPx-API") {
                    sh 'mvn clean package' 
                }
            }
        }

        stage("SonarQube Analysis") {
            steps {
                echo 'SonarQube Analysis'
                script {
                    def scannerHome = tool 'SonarScanner 6.2';
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            echo "Contents of APPx-API directory:"
                            ls -la ${WORK_DIR}/APPx-API
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=ronniemezzapesa_TP-Grupo01-Credicoop_6dd67d82-246a-453a-8d44-22a07f971c06 \
                            -Dsonar.sources=${WORK_DIR}/APPx-API/src/main/java \
                            -Dsonar.projectBaseDir=. \
                            -Dsonar.login=squ_73450ece2bf4747d944671b1353eb6e4a382f1a5
                        """
                    }
                }
            }
        }

        stage('Checkout remoto') {
            agent {
                label 'minikube'
            }
            steps {
                script {
                    echo 'Checking out SCM Jobs Project'
                    dir("${MINIKUBE_WORK_DIR}") {
                        git branch: 'main',
                            credentialsId: '12981d9c-635c-44b8-b0d2-739415ee7e77',
                            url: 'https://github.com/ronniemezzapesa/TP-Grupo01-Credicoop.git'
                    }
                }
            }
        }
        stage('Docker Build') {
            agent {
                label 'minikube'
            }
            steps {
                echo 'Building Docker Image'
                dir("${MINIKUBE_WORK_DIR}/TP-Grupo01-Credicoop/APPx-API") {
                    sh "docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ."
                }
            }
        }

        stage('Docker Push') {
            agent { label 'minikube' }
            steps {
                echo 'Pushing Docker Image'
                sh """
                    docker tag ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
                    docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
                """
            }
        }

        stage('Restart Deployment') {
            agent { label 'minikube' }
            steps {
                script {
                    sh """
                        minikube kubectl rollout restart deployment appx-api-deployment
                        minikube kubectl rollout status deployment appx-api-deployment
                    """
                }
            }
        }
    }
}
