pipeline {
    agent any

    environment {
        WORK_DIR = "/var/jenkins_home/${BUILD_ID}"
        MINIKUBE_WORK_DIR = "/home/produccion"
        DOCKER_IMAGE_NAME = "ronniemezzapesa/tp-credicoop"
        DOCKER_IMAGE_TAG = "latest"
        REPLICAS = 4
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out SCM-Jobs Project'
                dir("${WORK_DIR}") {
                    git branch: 'main',
                        credentialsId: '434adec4-f1be-45de-8f72-27082b7e1bcb',
                        url: 'https://github.com/ronniemezzapesa/TP-Grupo01-Credicoop.git'
                }
            }
        }

        stage('Build') {
            steps {
                echo 'Building the application'
                dir("${WORK_DIR}/APPx-API") {
                    sh 'mvn clean package' 
                }
            }
        }

        stage("SonarQube Analysis") {
            steps {
                echo 'SonarQube Analysis'
                script {
                    def scannerHome = tool 'SonarScanner 6.2';
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            echo "Contents of APPx-API directory:"
                            ls -la ${WORK_DIR}/APPx-API
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=ronniemezzapesa_TP-Grupo01-Credicoop_40ba5b44-730b-4615-829a-879d6d2291e9 \
                            -Dsonar.sources=${WORK_DIR}/APPx-API/src/main/java \
                            -Dsonar.projectBaseDir=. \
                            -Dsonar.login=squ_a235ece3842edf6054cbcab7b115464f8102449d
                        """
                    }
                }
            }
        }

        stage('Checkout remoto') {
            agent {
                label 'minikube'
            }
            steps {
                script {
                    echo 'Checking out SCM Jobs Project'
                    dir("${MINIKUBE_WORK_DIR}") {
                        git branch: 'main',
                            credentialsId: '434adec4-f1be-45de-8f72-27082b7e1bcb',
                            url: 'https://github.com/ronniemezzapesa/TP-Grupo01-Credicoop.git'
                    }
                }
            }
        }
        stage('Docker Build') {
            agent {
                label 'minikube'
            }
            steps {
                echo 'Building Docker Image'
                dir("${MINIKUBE_WORK_DIR}/TP-Grupo01-Credicoop/APPx-API") {
                    sh "docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ."
                }
            }
        }

        stage('Docker Push') {
            agent { label 'minikube' }
            steps {
                echo 'Pushing Docker Image'
                sh """
                    docker tag ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
                    docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
                """
            }
        }

        stage('Scale Deployment') {
            agent { label 'minikube' }
            steps {
                script {
                    echo "Escalando deployment a ${REPLICAS} replicas"
                    sh """
                        minikube kubectl -- scale deployment appx-api-deployment --replicas=${REPLICAS}
                    """
                }
            }
        }
    }
}