services:
  jenkins-agent:
    image: jenkins/agent
    container_name: jenkins-agent-1
    environment:
      - JENKINS_AGENT_NAME=VM-produccion
      - JENKINS_URL=http://192.168.232.132:8080/
      - JENKINS_SECRET=d6b0e1a6fd0f8ddec92554ad66a861695b992edea22bf10ea97159fdcad475a6
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge  
