volumes:
  grafana-data:
  prometheus-data:

networks:
  monitoring:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9050:9090"  
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml  
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
