global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.232.132:9050']  

  - job_name: 'jenkins'
    static_configs:
      - targets: ['192.168.232.132:8080']  
    metrics_path: '/prometheus'
