apiVersion: apps/v1
kind: Deployment
metadata:
  name: appx-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appx-api
  template:
    metadata:
      labels:
        app: appx-api
    spec:
      containers:
      - name: appx-api
        image: ronniemezzapesa/tp-credicoop:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_USER
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_URL
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret 
              key: POSTGRES_PASSWORD
  
      imagePullSecrets:
      - name: regcred  
