apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler #escalado horizontal de los pod# 
metadata:
        name: appx-api-hpa #nombre del hpa#
spec:
  scaleTargetRef: #parametrizacion con que pod trabajar
    apiVersion: apps/v1
    kind: Deployment # trabajo sobre un deployment
    name: appx-api-deployment #trabajo sobre este especifico deployment
  minReplicas:1 
  maxReplicas:5
  targetCPUUtilizationPercentage:50 
  # al 50 porciento de utilizacion del pod 
  # aumenta una replica, hasta 5 pod
  # caso contrario, desescalo si no los uso